<h1>Reading Notes</h1>
<h4>Raw material for future blogs!</h4>

<h2>The predictive mind</h2>
<ul>
	<li>
		High precision expectations increase the gain on prediction errors, the gain on the precision
		units drives changes in prediction units at higher levels. This translates to a top-down vs.
		bottom-up balancing dynamic. More global, long-term, and general representations will tend to
		respond to prediction errors with large gain. In contrast, more local, short-term and particular
		representations will respond to prediction errors with less gain. Here, prediction error is
		conceived as a learning signal, where the gain modulates how learning proceeds. A large gain
		biases in favour of learning in a global sense, where the brain seeks to encompass what happens
		in relatively sweeping, detail-poor generalizations that see patterns rather than individual
		differences.
		<br /><br />
		In contrast when there are low precision expectations there is a low gain on predictive error, therefore
		top-down predictions are given inordinate weight in perceptual inference. This is why hallucination
		is more common where sensory input is noisy e.g. A whispering crowd, a dark corner, white noise.
	</li>
	<li>Attention is nothing but optimisation of precision expectations.</li>
	<li>
		If the system has agency, then it can interact as a hidden cause with other hidden causes in the
		world. Therefore the systems model of the world needs to include a model of itself and its
		trajectory throughout the world just as it needs to model other hidden causes.
	</li>
	<li>
		Now consider how action comes about in a system that models itself and which can act. The
		representations of predicted sensory input are counterfactual in the sense that they say how
		sensory input would change if the system were to act in a certain way. Given that things are not
		actually that way, a prediction error is induced, which can be minimized by acting in the pre
		scribed way. The mechanism for being a system that acts is thus nothing more than the generation
		of prediction error and the ability to change the body's configuration such that the antecedent
		of the counterfactual actually obtains and error is suppressed. Action therefore does not come
		about through some complex computation of motor commands that control the muscles of the body.
		In simple terms, what happens is instead that the muscles are told to move as long as there is
		prediction error. The muscles of the body are thus at the mercy of the prediction error
		generated by the brain's model of the way the world is expected to be like but isn't. Prediction
		error is then the simple mechanism that controls action.
	</li>
	<li>
		Because of who we are we expect to be in certain states. So we prophesy that we will be in those
		states, and by the very act of prophesying those states we induce a prediction error that causes
		us to end up in those states. By predicting it we make it so.
	</li>
	<li>
		Binding is essentially a statistically based inner fantasy, shaped by the brain's generative
		model of the world. Examples include rubber hand illusion, Treismans lines and binocular
		rivalry.
	</li>
	<li>
		The proposal is that cognitive impenetrability (inability of top down expectation to change
		perception) occurs when prediction error is sufficiently suppressed at relatively early
		processing stages. Even if the higher-level belief is part of a model generating predictions,
		these predictions generate little prediction error because activity at lower levels is already
		low. There is no special mechanism or anatomical architecture needed to explain impenetrability,
		it just so happens that given a certain level of uncertainty and certain priors, prediction
		error is efficiently suppressed very earlier on. One prediction flowing from this proposal is
		then that if more noise were introduced into the situation, for example by degrading the stimuli
		or provide ing a context suggesting added ambiguity, then the prior high-level belief in equal
		lengths could be allocated more weight.
	</li>
	<li>
		Scale errors. Children between 1.5 and 2.5 years can be brought to display perplexing errors of
		scale. In Judy Deloache's (DeLoache, Uttal et al. 2004) Delightful study, children of this age
		were first given an opportunity to play with full scale toys like plastic chairs to sit on,
		slides to slide down, or cars to sit in and drive around in the 'Little Tikes Cozy Coupe').
		Subsequently, they were given the opportunity to play with a miniature model of the same toy.Now
		they display scale errors: they will sometimes behave as if they have not noticed the change in
		scale. In the case of the Cozy Coupe, they try to climb in to the miniature car and will persist
		in this behaviour for some time, somewhat perplexed that their nice toy is not cooperating any
		longer.
	</li>
	<li>
		When one is actually in an out of control situation one is failing to minimize prediction error
		in active inference and failing to revise hypotheses, in response the chosen trajectory causes
		much error and no better trajectory seems available. It is a situation where there is larger
		than expected imprecision in active inference and no clear way to fix things. In that situation
		it makes sense to let prior beliefs guide perceptual inference: instead of being guided by the
		senses to failure, one should decrease the gain (precision) on the input and rely more on prior
		belief.
	</li>
	<li>
		Conscious experience is like a fantasy or virtual reality constructed to keep sensory input at
		bay. Differing from mental imagery and dreaming that are not intended to keep sensory input at
		bay.
	</li>
	<li>
		To a certain degree, different sensory modalities and their prediction error minimization
		mechanisms are shielded from each other to provide independent evidence from the environment,
		this helps prevent one modality from laterally overdetermining information from other
		modalities.
	</li>
	<li>
		Having independent sources of evidence facilitates reality testing. Hence, even if expected
		precisions are suboptimal in one sensory domain they could in principle be corrected by the
		evidence delivered via other sensory sources. For example, if the auditory sense is suboptimal
		it could perhaps be adjusted via the more optimal estimates from visual and tactile estimates.
		One obstacle may be if the problem persists in a sensory channel for which there are no other
		relevant sensory sources of information. This speaks to the preponderance of delusions that
		arguably occur in sensory domains where it is hard to avail oneself of multiple independent
		sources of evidence that would directly engage prediction error at the right spatiotemporal
		fineness of grain. Thus, emotional, agency-related, proprioceptive, body, and self-related
		contents are often delusion prone and fall in this evidentially insulated category. It is also
		conceivable that as intractable interpretations in these insulated sensory domains become part
		of one's doxastic bedrock, they can lead to more prolific delusional systems.
	</li>
	<li>
		Dopamine regulates signal to noise ratio, delusion formation begins when sensory information is
		predicted to be less precise, more noisey and more uncertain than it actually is, this decreases
		the gain on sensory input (less prediction errors propogating up heiracrchy) and heightens the
		reliance on top down priors. The dampened down error signal is inefficient at regulating ongoing
		revision of prior belief meaning that priors are more likely to stray away from reality.
		Relatively small (but significant) prediction errors are treated as noise instead of signal,
		while larger prediction errors may stand out as being expectionally salient against the
		background of subdued prediction error. This leads to improbable beliefs detached from reality
		and insulated from sensory evidence that would force revision. <br /><br /> Autism on the other hand
		could be explained by increased Imprecision of top down predictions and increased expectation of
		precise sensory input. Hence prediction error from the sensory input is highly weighed resulting
		in greater reliance on the senses, a preoccupation on local sensory content, intolerance to change
		in circumstances and decreased ability to predict long term regularities, global models and complex,
		deep hidden causes in social interactions.
	</li>
	<li>
		While consciousness and attention are often associated, it is possible to unconsciously attend
		to something (flash suppression study). Conscious perception is determined by the hypothesis
		that best minimises prediction error, attention is directed where there is the greatest expected
		precision of sensory input. Over time due to statistical regularities in nature e.g. Low light
		at dusk. we learn where and when to expect high precision sensory input, we know where to look
		and when to listen. Global broadcasting allows information to be more efficiently broadcast,
		resulting in "ignition" of the prefronto-parietal network. Global ignition is achieved when a
		hypothesis about the world is better able to explain away input than its competitor, and
		therefore achieves higher posterior probability. What counts as being better able to explain
		away input is modulated by the expected levels of noise and uncertainty, this is what sets the
		threshold for ignition. Upon ignition, the perceptual content is made available to consumer
		systems throughout the brain, and can guide action and decision-making, and be introspectively
		reported as a conscious experience. The reason we have a unified experience of consciousness
		(from one perspective) is that it is impossible to simultaneously engage in the active inference
		of two opposing hypotheses. In a trivial example of binocular rivalry if you have two people,
		one can see a house and the other a face. An indivual is forced to flip between the two because
		they cannot sample the scene with their eyes while maintaining contradictory hypotheses.
	</li>
	<li>
		We are all virtuoso novelists, who find ourselves engaged in all sorts of behav iour, more or
		less unified, but sometimes disunified, and we always put the best "faces" on it we can. We try
		to make all of our material cohere into a single good story. And that story is our
		autobiography. The chief fictional character at the centre of that autobiography is one's self.
	</li>
</ul>

<h2>Surfing Uncertainty - Andy Clark</h2>
<ul>
	<li>
		Handwritten number identifier: It helps to note that the entire digit recognition network,
		Hinton remarks, has only about as many parameters as 0.002 cubic millimeters of mouse cortex'
		and that 'several hundred networks of this complexity would fit within a single voxel of a high
		resolution fMRI scan'
	</li>

	<li>
		Attention and expectation thus look to operate as distinct elements within the inferential
		cascade in the way PP suggests. Attention enhances (increases the gain on the neural responses
		associated with select prediction errors, while expectation dampens those neural responses that
		are in line with the expectation.
	</li>

	<li>
		The primary motor cortex is no more or less a motor cortical area than striate (Visual) cortex.
		The only difference between the motor cortex and visual cortex is that one predicts retino topic
		input while the other predicts proprioceptive input from the motor plant.
	</li>

	<li>
		Perhaps the dream state arises from disruptions in hierarchical processing such that sensory
		firing is not constrained by top-down prior information and inferences are accepted with out
		question owing to an attenuation of the prediction-error signal from lower to higher levels.
	</li>

	<li>
		Laeng and Sulutvedt (2014) show, surprisingly, that the act of imagining can even impact pupil
		dilation and shrinkage. In this work, subjects were exposed to images of triangles of varying
		brightness. During exposure, the subject's pupils responded in the usual fashion, by dilating
		(widening) when the images were darker, and shrinking when they were lighter. When asked to
		imagine the same triangles, the same pupillary responses of dilation and shrinkage occurred.
		This result is striking since pupil size is something over which most subjects cannot exercise
		any form of conscious control, leading the experimenters to comment that 'the observed pupillary
		adjustments to imaginary light present a strong case for accounts of mental imagery as a process
		based on brain states similar to those that arise in perception' (p. 188) Such responses might
		serve, the authors suggest to prepare the eyes for anticipated (perhaps potentially damaging or
		dangerously inadequate) levels of light.
	</li>

	<li>
		Reich et al. (2011) found evidence that VWFA is actually tracking something even more abstract
		than visual word form. It appears to be tracking word form regardless of the modality of the
		transducing stream. Thus, the very same area is activated in congenital blind subjects during
		Braille reading. The fact that the early in here is tactile rather than visual makes no
		difference to the recruit ment of VWFA. This supports the idea (Pascual-Leone & Hamilton 2001)
		of such brain areas as 'metamodal operators that are 'defined by a given computation that is
		applied regardless of the sensory input received
	</li>

	<li>
		I think we should resist the claim that what perceive is best understood as a kind of
		hypothesis, model, fantasy ar virtual reality. The temptation to think so, it seems to me, rests
		on two mistakes. The first mistake is to conceive of inference-based routes to adaptive response
		as introducing a kind of representational veil between agent and world. Instead, it is only the
		structured probabilistic know-how distilled from prediction-driven learning that enables us to
		see through the veil of surface statistics to the world of distal interacting causes itself.
	</li>

	<li>
		The basic idea was that delusions might flow from a single underlying cause: falsely generated
		and highly weighted (high-precision) waves of prediction error. The key distubance is thus a
		disturbance in metacognition for it is the weighing (precision) assigned to these error signals
		that makes them so functionally potent, positioning them to drive the system into plasticity and
		learning, forming and recruiting increasingly bizarre hypotheses so as to accommodate the
		unrelenting waves of (apparently) reliable and salient yet persistently unexplained information.
	</li>

	<li>
		Movement ensues when the sensory (proprioceptive) consequences of an action are strongly
		predicted. Since those consequences (specified as a temporal trajectory of proprioceptive
		sensations) are not yet actual, prediction error occurs, which is then quashed by the unfolding
		of the action.
	</li>
</ul>

<h2>Robert Brandom - discursive practices</h2>
<p>
	Page 7 In short, according to agent semantics, a linguistic utterance in communication is,
	literally, a speech act: a rational action carried out by the speaker with a set of specific,
	complex intentions to overtly give her interlocutors reasons to change their mind and/or to behave
	in certain ways. Linguistic communication is successful, in this view, to the extent that the
	interlocutors recognize the speaker's intentions; that is, that they recognize her as openly
	giving them a reason to change their minds and/or to behave in a specific way.
	<br /><br />
	Page 16 While a sentence's or linguistic performance's inferential role alone constitutes its meaning
	(its propositional content), Brandom agrees with proponents of the Received View that every propositionally
	contentful item has a representational dimension. However, contra those proponents he maintains that
	this representational dimension, rather than playing any part in constituting the item's propositional
	contentedness, is a non-semantic and, as it were, epiphenomenal add-on to the item's inferential role,
	which alone constitutes its meaning. For Brandom, representation is non semantic; it is philosophically
	explained in terms of meaning qua inferential role (together with other per se non-semantic, structural
	features of discursive practices), rather than vice versa.
	<br /><br />
	Page 38 The norms determining the location of actual or potential judgments that in the space of reason
	are the content that p. It follows that, on Brandom's view, the cognitive state or activity of judging
	that p and the content that p, in abstraction from the state or the activity, cannot be philosophically
	characterized except in terms of each other. Any state or activity of judging has a role in reasoning,
	hence a particular location in the space of reasons, hence a content that p. And any content that p
	is a set of norms constrain ing a subject's justificatory, amplative, and critical reasoning, that
	is, her activity of maintaining and updating her system of theoretical or practical judgments that
	p - her system of states of judging concepts are the sub-propositional semantic components of propositional
	contents that p.
	<br /><br />
	Page 53 Metaphysically speaking, a content that p is nothing but a relatum of a bundle of norms of
	reasoning, relating that relatum to other such relata - other contents that q, that r, that s.
	<br /><br />
	Page 61 Brandom concludes that discursive practices where the only speech acts made are assertions.
	Assertional practices - are strictly speaking the only autonomous discursive practices.
	<br /><br />
	Page 66 If P acknowledges a commitment Vz she must avow Vz in response, whereas if she doesn't she
	must disavow acknowledgment to Vz by (let's say) vocalizing Vz by shaking her head. Such a disavowal
	does not express anything like logical negation. That is, disavowing Vz is not the same as avowing
	Not-Vz; in autonomous discursive practices no type of vocalization is the logical negation of another
	type of vocalization. Rather someone who disavows Vz thereby expresses non-acknowledgment of commitment
	to Vz. Page 75 Unless a scorekeeper has reason to regard the player as an unreliable observer or as
	internally incoherent, or acknowledges a commitment to an incompatible claim herself, she must attribute
	default entitlement to these observation reports to the player. This feature of our practices is recognizably
	anti-Cartesian and classical American Pragmatist. According to it, withholding the attribution of entitlement
	to a type from a player ("doubt") is itself something a scorekeeper needs to be entitled to. Page 81
	Clearly, Brandom's theory is a version of linguistic pragmatism, the view that only speakers of public
	natural languages are able to think conceptually.
	<br /><br />
	Brandom's theory is a version of functionalism, in the sense that Brandom regards the defining feature
	of assertion and belief, as well as of propositional content in the abstract, as the functional role
	of these items in the game of giving and asking for reasons.
	<br /><br />
	Page 86 In general, truth plays no explanatory role whatsoever in semantics, logic, and epistemology,
	according to Brandom the normative pragmatic deontic scorekeeping vocabulary does all the explanatory
	work and Brandom is, in this sense, a deflationism about truth.
	<br /><br />
	Page 131 In short, epistemic reliability, albeit external to the individual in the described, limited
	sense, is internal to the social practices of giving and asking for reasons and assessing reliability,
	in the sense that all practitioners can in principle (though not always in practice) find out, in each
	case at hand, through sufficiently rigorous and sustained engagement in the practice, whether some
	is epistetemically reliable. The status of an observational belief that p as reliably formed adds to
	the beliefs standing in the space of reasons, according to Brandom, in the sense that the belief is
	essentially a reason for others to form the belief that p.
	<br /><br />
	Page 138 Brandom regards the distinction between the observational and the theoretical as methodological,
	rather than ontological.
	<br /><br />
	Page n/a Acknowledged assertional commitments are beliefs, in the empirical psychological, causally
	relevant sense of "belief." Acknowledged practical commitments, according to Brandom, are intentions,
	in the empirical psychological, causally relevant sense of "intention".
	<br /><br />
	Page 156 By claiming "If P then Q" the speaker makes explicit his acknowledgement of an inferential
	commitment from P to Q (circumstances of application), and the audience's proper default response to
	the claim, normatively expected by the speaker, is to acknowledge an inferential commitment from P
	to Q (consequences of application). But semantically the claim simply says that if P then Q. The proposition
	expressed does not involve the concepts consequence, speaker-acknowledged inferential commitment or
	obligation to acknowledge commitment, and thus does not semantically describe the circumstances and
	consequences it pragmatically makes explicit.
	<br /><br />
	Brandom subscribes to logical expressivism and modal realism
	<br /><br />
	Page 168 Ordinary empirical concepts do not only describe how things actually are but also already
	comprise, as an essential aspect of their substitution semantic role, implicit information as to how
	things might or must be. Thus, thought and talk about how things actually are cannot be divorced from
	implicit considerations of how they must or might be.
	<br /><br />
	Page 194 According to Brandom, communicative success does not require transporting an unchanging semantic
	item via speech from one mind to another, but rather requires from each participant an appreciation
	of every interlocutor's individual understanding of the linguistic performances exchanged. Communicating
	successfully, thinks Brandom, is like engaging in a skillful dance together, where the varying moves
	made by each partner - the various linguistic understandings of what is said, distributed over the
	interlocutors - amalgamate into one harmonious interaction.
	<br /><br />
	Page 198 (Discussing the bracketing theory) For example, E may falsely believe that arthritis can strike
	both joints and thighs, hence acknowledge a substitutional commitment from " is arthritic" to "_ strikes
	joints and thighs", while D may know that arthritis may strike only the joints, hence acknowledge a
	substitutional commitment from " is arthritic" to "strikes only joints." Yet this difference in understanding
	of "arthritis" can be bracketed for the purposes of the dialogue above and, indeed, D and E may never
	notice it, without thwarting communicative success. What matters for communicative success is, first,
	that they both have at least the superficial, partial understanding of "arthritis" required for the
	purposes of their particular conversation - say, that they both acknowledge substitutional commitments
	from "_is arthritic " to "_ is some kind of ailment".
</p>

<style>
	h1,
	h2,
	h3,
	h4,
	h5,
	p,
	a {
		margin-left: 2.5rem;
		margin-right: 2.5rem;
	}

	li {
		margin: 1rem;
		font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
	}
</style>
