<h1>Reading Notes</h1>
<h4>Raw material for future blogs!</h4>

<h2>The predictive mind</h2>
<ul>
	<blockquote>
		High precision expectations increase the gain on prediction errors, the gain on the precision
		units drives changes in prediction units at higher levels. This translates to a top-down vs.
		bottom-up balancing dynamic. More global, long-term, and general representations will tend to
		respond to prediction errors with large gain. In contrast, more local, short-term and particular
		representations will respond to prediction errors with less gain. Here, prediction error is
		conceived as a learning signal, where the gain modulates how learning proceeds. A large gain
		biases in favour of learning in a global sense, where the brain seeks to encompass what happens
		in relatively sweeping, detail-poor generalizations that see patterns rather than individual
		differences.
		<br /><br />
		In contrast when there are low precision expectations there is a low gain on predictive error, therefore
		top-down predictions are given inordinate weight in perceptual inference. This is why hallucination
		is more common where sensory input is noisy e.g. A whispering crowd, a dark corner, white noise.
	</blockquote>
	<blockquote>Attention is nothing but optimisation of precision expectations.</blockquote>
	<blockquote>
		If the system has agency, then it can interact as a hidden cause with other hidden causes in the
		world. Therefore the systems model of the world needs to include a model of itself and its
		trajectory throughout the world just as it needs to model other hidden causes.
	</blockquote>
	<blockquote>
		Now consider how action comes about in a system that models itself and which can act. The
		representations of predicted sensory input are counterfactual in the sense that they say how
		sensory input would change if the system were to act in a certain way. Given that things are not
		actually that way, a prediction error is induced, which can be minimized by acting in the pre
		scribed way. The mechanism for being a system that acts is thus nothing more than the generation
		of prediction error and the ability to change the body's configuration such that the antecedent
		of the counterfactual actually obtains and error is suppressed. Action therefore does not come
		about through some complex computation of motor commands that control the muscles of the body.
		In simple terms, what happens is instead that the muscles are told to move as long as there is
		prediction error. The muscles of the body are thus at the mercy of the prediction error
		generated by the brain's model of the way the world is expected to be like but isn't. Prediction
		error is then the simple mechanism that controls action.
	</blockquote>
	<blockquote>
		Because of who we are we expect to be in certain states. So we prophesy that we will be in those
		states, and by the very act of prophesying those states we induce a prediction error that causes
		us to end up in those states. By predicting it we make it so.
	</blockquote>
	<blockquote>
		Binding is essentially a statistically based inner fantasy, shaped by the brain's generative
		model of the world. Examples include rubber hand illusion, Treismans lines and binocular
		rivalry.
	</blockquote>
	<blockquote>
		The proposal is that cognitive impenetrability (inability of top down expectation to change
		perception) occurs when prediction error is sufficiently suppressed at relatively early
		processing stages. Even if the higher-level belief is part of a model generating predictions,
		these predictions generate little prediction error because activity at lower levels is already
		low. There is no special mechanism or anatomical architecture needed to explain impenetrability,
		it just so happens that given a certain level of uncertainty and certain priors, prediction
		error is efficiently suppressed very earlier on. One prediction flowing from this proposal is
		then that if more noise were introduced into the situation, for example by degrading the stimuli
		or provide ing a context suggesting added ambiguity, then the prior high-level belief in equal
		lengths could be allocated more weight.
	</blockquote>
	<blockquote>
		Scale errors. Children between 1.5 and 2.5 years can be brought to display perplexing errors of
		scale. In Judy Deloache's (DeLoache, Uttal et al. 2004) Delightful study, children of this age
		were first given an opportunity to play with full scale toys like plastic chairs to sit on,
		slides to slide down, or cars to sit in and drive around in the 'Little Tikes Cozy Coupe').
		Subsequently, they were given the opportunity to play with a miniature model of the same toy.Now
		they display scale errors: they will sometimes behave as if they have not noticed the change in
		scale. In the case of the Cozy Coupe, they try to climb in to the miniature car and will persist
		in this behaviour for some time, somewhat perplexed that their nice toy is not cooperating any
		longer.
	</blockquote>
	<blockquote>
		When one is actually in an out of control situation one is failing to minimize prediction error
		in active inference and failing to revise hypotheses, in response the chosen trajectory causes
		much error and no better trajectory seems available. It is a situation where there is larger
		than expected imprecision in active inference and no clear way to fix things. In that situation
		it makes sense to let prior beliefs guide perceptual inference: instead of being guided by the
		senses to failure, one should decrease the gain (precision) on the input and rely more on prior
		belief.
	</blockquote>
	<blockquote>
		Conscious experience is like a fantasy or virtual reality constructed to keep sensory input at
		bay. Differing from mental imagery and dreaming that are not intended to keep sensory input at
		bay.
	</blockquote>
	<blockquote>
		To a certain degree, different sensory modalities and their prediction error minimization
		mechanisms are shielded from each other to provide independent evidence from the environment,
		this helps prevent one modality from laterally overdetermining information from other
		modalities.
	</blockquote>
	<blockquote>
		Having independent sources of evidence facilitates reality testing. Hence, even if expected
		precisions are suboptimal in one sensory domain they could in principle be corrected by the
		evidence delivered via other sensory sources. For example, if the auditory sense is suboptimal
		it could perhaps be adjusted via the more optimal estimates from visual and tactile estimates.
		One obstacle may be if the problem persists in a sensory channel for which there are no other
		relevant sensory sources of information. This speaks to the preponderance of delusions that
		arguably occur in sensory domains where it is hard to avail oneself of multiple independent
		sources of evidence that would directly engage prediction error at the right spatiotemporal
		fineness of grain. Thus, emotional, agency-related, proprioceptive, body, and self-related
		contents are often delusion prone and fall in this evidentially insulated category. It is also
		conceivable that as intractable interpretations in these insulated sensory domains become part
		of one's doxastic bedrock, they can lead to more prolific delusional systems.
	</blockquote>
	<blockquote>
		Dopamine regulates signal to noise ratio, delusion formation begins when sensory information is
		predicted to be less precise, more noisey and more uncertain than it actually is, this decreases
		the gain on sensory input (less prediction errors propogating up heiracrchy) and heightens the
		reliance on top down priors. The dampened down error signal is inefficient at regulating ongoing
		revision of prior belief meaning that priors are more likely to stray away from reality.
		Relatively small (but significant) prediction errors are treated as noise instead of signal,
		while larger prediction errors may stand out as being expectionally salient against the
		background of subdued prediction error. This leads to improbable beliefs detached from reality
		and insulated from sensory evidence that would force revision. <br /><br /> Autism on the other hand
		could be explained by increased Imprecision of top down predictions and increased expectation of
		precise sensory input. Hence prediction error from the sensory input is highly weighed resulting
		in greater reliance on the senses, a preoccupation on local sensory content, intolerance to change
		in circumstances and decreased ability to predict long term regularities, global models and complex,
		deep hidden causes in social interactions.
	</blockquote>
	<blockquote>
		While consciousness and attention are often associated, it is possible to unconsciously attend
		to something (flash suppression study). Conscious perception is determined by the hypothesis
		that best minimises prediction error, attention is directed where there is the greatest expected
		precision of sensory input. Over time due to statistical regularities in nature e.g. Low light
		at dusk. we learn where and when to expect high precision sensory input, we know where to look
		and when to listen. Global broadcasting allows information to be more efficiently broadcast,
		resulting in "ignition" of the prefronto-parietal network. Global ignition is achieved when a
		hypothesis about the world is better able to explain away input than its competitor, and
		therefore achieves higher posterior probability. What counts as being better able to explain
		away input is modulated by the expected levels of noise and uncertainty, this is what sets the
		threshold for ignition. Upon ignition, the perceptual content is made available to consumer
		systems throughout the brain, and can guide action and decision-making, and be introspectively
		reported as a conscious experience. The reason we have a unified experience of consciousness
		(from one perspective) is that it is impossible to simultaneously engage in the active inference
		of two opposing hypotheses. In a trivial example of binocular rivalry if you have two people,
		one can see a house and the other a face. An indivual is forced to flip between the two because
		they cannot sample the scene with their eyes while maintaining contradictory hypotheses.
	</blockquote>
	<blockquote>
		We are all virtuoso novelists, who find ourselves engaged in all sorts of behav iour, more or
		less unified, but sometimes disunified, and we always put the best "faces" on it we can. We try
		to make all of our material cohere into a single good story. And that story is our
		autobiography. The chief fictional character at the centre of that autobiography is one's self.
	</blockquote>
</ul>

<h2>Surfing Uncertainty - Andy Clark</h2>
<ul>
	<blockquote>
		It helps to note that the entire digit recognition network,
		Hinton remarks, has only about as many parameters as 0.002 cubic millimeters of mouse cortex'
		and that 'several hundred networks of this complexity would fit within a single voxel of a high
		resolution fMRI scan'
	</blockquote>

	<blockquote>
		Attention and expectation thus look to operate as distinct elements within the inferential
		cascade in the way PP suggests. Attention enhances (increases the gain on the neural responses
		associated with select prediction errors, while expectation dampens those neural responses that
		are in line with the expectation.
	</blockquote>

	<blockquote>
		The primary motor cortex is no more or less a motor cortical area than striate (Visual) cortex.
		The only difference between the motor cortex and visual cortex is that one predicts retino topic
		input while the other predicts proprioceptive input from the motor plant.
	</blockquote>

	<blockquote>
		Perhaps the dream state arises from disruptions in hierarchical processing such that sensory
		firing is not constrained by top-down prior information and inferences are accepted with out
		question owing to an attenuation of the prediction-error signal from lower to higher levels.
	</blockquote>

	<blockquote>
		Laeng and Sulutvedt (2014) show, surprisingly, that the act of imagining can even impact pupil
		dilation and shrinkage. In this work, subjects were exposed to images of triangles of varying
		brightness. During exposure, the subject's pupils responded in the usual fashion, by dilating
		(widening) when the images were darker, and shrinking when they were lighter. When asked to
		imagine the same triangles, the same pupillary responses of dilation and shrinkage occurred.
		This result is striking since pupil size is something over which most subjects cannot exercise
		any form of conscious control, leading the experimenters to comment that 'the observed pupillary
		adjustments to imaginary light present a strong case for accounts of mental imagery as a process
		based on brain states similar to those that arise in perception' (p. 188) Such responses might
		serve, the authors suggest to prepare the eyes for anticipated (perhaps potentially damaging or
		dangerously inadequate) levels of light.
	</blockquote>

	<blockquote>
		Reich et al. (2011) found evidence that VWFA is actually tracking something even more abstract
		than visual word form. It appears to be tracking word form regardless of the modality of the
		transducing stream. Thus, the very same area is activated in congenital blind subjects during
		Braille reading. The fact that the early in here is tactile rather than visual makes no
		difference to the recruit ment of VWFA. This supports the idea (Pascual-Leone & Hamilton 2001)
		of such brain areas as 'metamodal operators that are 'defined by a given computation that is
		applied regardless of the sensory input received
	</blockquote>

	<blockquote>
		I think we should resist the claim that what perceive is best understood as a kind of
		hypothesis, model, fantasy ar virtual reality. The temptation to think so, it seems to me, rests
		on two mistakes. The first mistake is to conceive of inference-based routes to adaptive response
		as introducing a kind of representational veil between agent and world. Instead, it is only the
		structured probabilistic know-how distilled from prediction-driven learning that enables us to
		see through the veil of surface statistics to the world of distal interacting causes itself.
	</blockquote>

	<blockquote>
		The basic idea was that delusions might flow from a single underlying cause: falsely generated
		and highly weighted (high-precision) waves of prediction error. The key distubance is thus a
		disturbance in metacognition for it is the weighing (precision) assigned to these error signals
		that makes them so functionally potent, positioning them to drive the system into plasticity and
		learning, forming and recruiting increasingly bizarre hypotheses so as to accommodate the
		unrelenting waves of (apparently) reliable and salient yet persistently unexplained information.
	</blockquote>

	<blockquote>
		Movement ensues when the sensory (proprioceptive) consequences of an action are strongly
		predicted. Since those consequences (specified as a temporal trajectory of proprioceptive
		sensations) are not yet actual, prediction error occurs, which is then quashed by the unfolding
		of the action.
	</blockquote>
</ul>



<style>
	h1,
	h2,
	h4 {
		margin-left: 2.5rem;
		margin-right: 2.5rem;
	}

	blockquote{
		margin: 1rem;
		padding: 1rem;
		font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
		background-color: white;
		border: solid black thin;
	}
</style>
